name: home-services

include:
  - compose.immich.yaml
  - compose.hoarder.yaml

networks:
  downloads:
    driver: bridge
  media:
    driver: bridge

services:
  caddy:
    container_name: caddy
    image: serfriz/caddy-cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - IMMICH_DOMAIN=${IMMICH_DOMAIN}
      - PLEX_DOMAIN=${PLEX_DOMAIN}
      - QBITTORRENT_DOMAIN=${QBITTORRENT_DOMAIN}
      - SONARR_DOMAIN=${SONARR_DOMAIN}
      - HOMEASSISTANT_DOMAIN=${HOMEASSISTANT_DOMAIN}
      - N3P_DOMAIN=${N3P_DOMAIN}
      - HOARDER_DOMAIN=${HOARDER_DOMAIN}
    volumes:
      - ${CONFIG_ROOT}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${CONFIG_ROOT}/caddy/certs:/certs
      - ${CONFIG_ROOT}/caddy/config:/config
      - ${CONFIG_ROOT}/caddy/data:/data
      - ${CONFIG_ROOT}/caddy/sites:/srv
    network_mode: "host"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - ${CONFIG_ROOT}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    depends_on:
      - mosquitto

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    user: "${PUID}:${PGID}"
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ${CONFIG_ROOT}/mosquitto/config:/mosquitto/config
      - ${CONFIG_ROOT}/mosquitto/data:/mosquitto/data
      - ${CONFIG_ROOT}/mosquitto/log:/mosquitto/log

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "9091:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=${QB_VPN_ENABLED}
      - VPN_PROVIDER=${QB_VPN_PROVIDER}
      - VPN_CONF=${QB_VPN_CONF}
      - VPN_LAN_NETWORK=${QB_VPN_LAN_NETWORK}
      - VPN_EXPOSE_PORTS_ON_LAN=9091/tcp
      - VPN_KEEP_LOCAL_DNS=true
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_FIREWALL_TYPE=auto
    volumes:
      - ${CONFIG_ROOT}/qbittorrent/config:/config
      - ${DOWNLOADS_DIR}:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    networks:
      - downloads

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/sonarr/data:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - qbittorrent
    networks:
      - downloads

  byparr:
    container_name: byparr
    image: ghcr.io/thephaseless/byparr:main
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - downloads

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - downloads

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - ${CONFIG_ROOT}/plex/database:/config
      - ${CONFIG_ROOT}/plex/transcode:/transcode
      - ${DATA_ROOT}:/data
    networks:
      - media
  # yt-dlp-webui:
  #   image: marcobaobao/yt-dlp-webui
  #   container_name: yt-dlp-webui
  #   ports:
  #     - 3033:3033
  #   volumes:
  #     - ${DOWNLOADS_DIR}:/downloads
  #   restart: unless-stopped
