include:
  - immich/compose.yaml

networks:
  downloads:
    driver: bridge
  media:
    driver: bridge

services:
  caddy:
    image: serfriz/caddy-cloudflare-ddns:latest
    restart: unless-stopped
    container_name: caddy
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - BASE_DOMAIN=${BASE_DOMAIN}
      - IMMICH_DOMAIN=${IMMICH_DOMAIN}
      - HOMEPAGE_DOMAIN=${HOMEPAGE_DOMAIN}
      - PLEX_DOMAIN=${PLEX_DOMAIN}
      - QBITTORRENT_DOMAIN=${QBITTORRENT_DOMAIN}
      - SONARR_DOMAIN=${SONARR_DOMAIN}
      - RADARR_DOMAIN=${RADARR_DOMAIN}
      - HOMEASSISTANT_DOMAIN=${HOMEASSISTANT_DOMAIN}
      - JELLYFIN_DOMAIN=${JELLYFIN_DOMAIN}
      - GLANCES_DOMAIN=${GLANCES_DOMAIN}
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/certs:/certs
      - ./config/caddy/config:/config
      - ./config/caddy/data:/data
      - ./config/caddy/sites:/srv
    network_mode: "host"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: ${PUID}
      PGID: ${PGID}

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - ./config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "9091:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=${VPN_ENABLED}
      - VPN_PROVIDER=${VPN_PROVIDER}
      - VPN_CONF=${VPN_CONF}
      - VPN_LAN_NETWORK=${VPN_LAN_NETWORK}
      - VPN_EXPOSE_PORTS_ON_LAN=9091/tcp
      - VPN_KEEP_LOCAL_DNS=true
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_FIREWALL_TYPE=auto
    volumes:
      - ./config/qbittorrent/config:/config
      - ${DOWNLOADS_DIR}:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    networks:
      - downloads

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr/data:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - qbittorrent
    networks:
      - downloads

  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ./config/radarr/data:/config
  #     - ${MOVIES_DIR}:/movies
  #     - ${DOWNLOADS_DIR}:/downloads
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped
  #   depends_on:
  #     - qbittorrent
  #   networks:
  #     - downloads

  byparr:
    image: ghcr.io/thephaseless/byparr:main
    container_name: byparr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - downloads

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - downloads

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - ./config/plex/database:/config
      - ./config/plex/transcode:/transcode
      - ${MEDIA_ROOT}:/data
    networks:
      - media
  # jellyfin:
  #   image: lscr.io/linuxserver/jellyfin:latest
  #   container_name: jellyfin
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - JELLYFIN_PublishedServerUrl=${JELLYFIN_DOMAIN}
  #   volumes:
  #     - ./config/jellyfin/config:/config
  #     - ${TV_DIR}:/data/tvshows
  #     - ${MOVIES_DIR}:/data/movies
  #   ports:
  #     - 8096:8096
  #     - 8920:8920
  #     - 7359:7359/udp
  #     - 1900:1900/udp
  #   restart: unless-stopped
  #   networks:
  #     - media
  # yt-dlp-webui:
  #   image: marcobaobao/yt-dlp-webui
  #   container_name: yt-dlp-webui
  #   ports:
  #     - 3033:3033
  #   volumes:
  #     - ${DOWNLOADS_DIR}:/downloads
  #   restart: unless-stopped
  glances:
    image: nicolargo/glances:latest
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
      - ./config/glances/glances.conf:/etc/glances/glances.conf
    environment:
      - "GLANCES_OPT=-w"
  mosquitto:
    image: eclipse-mosquitto:2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./config/mosquitto/config:/mosquitto/config
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log
